"""
Document processing pipeline worker.

Runs in a background thread after a document is uploaded:
  1. Extract text (via LangChain loaders from S3)
  2. Chunk the text (via LangChain RecursiveCharacterTextSplitter)
  3. Embed + store in Chroma Cloud (dense Qwen + sparse Splade → hybrid search)
  4. Update processing_status and page/chunk counts on the Document

Uses ProcessingJob for real-time progress tracking.
"""

import logging
import threading
from datetime import datetime, timezone

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.core.config.settings import settings
from app.services.text_extraction import extract_text
from app.services.chunking import chunk_text

logger = logging.getLogger(__name__)


def run_pipeline(document_id: str) -> None:
    """
    Entry point for the background thread.
    Creates its own DB session (threads cannot share SQLAlchemy sessions).
    """
    engine = create_engine(
        settings.DATABASE_URL,
        connect_args={"check_same_thread": False},
    )
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()

    try:
        _execute_pipeline(db, document_id)
    except Exception as exc:
        logger.exception("Pipeline failed for document %s: %s", document_id, exc)
        _mark_failed(db, document_id, str(exc))
    finally:
        db.close()


def _execute_pipeline(db, document_id: str) -> None:
    from app.models.document import Document
    from app.models.processing_job import ProcessingJob

    # ── Load document ────────────────────────────────────────────────────────
    doc: Document | None = db.query(Document).filter(Document.id == document_id).first()
    if not doc:
        logger.error("Document %s not found in DB — skipping pipeline", document_id)
        return

    # ── Create ProcessingJob ──────────────────────────────────────────────────
    job = ProcessingJob(
        document_id=document_id,
        status="running",
        progress=0,
        current_step="extracting",
        started_at=datetime.now(timezone.utc),
    )
    db.add(job)
    doc.processing_status = "extracting"
    db.commit()

    # ── Step 1: Extract text from S3 ─────────────────────────────────────────
    logger.info("[Pipeline] Extracting text for document %s (s3_key=%s)", document_id, doc.s3_key)
    full_text, page_count = extract_text(doc.s3_key, doc.file_type)

    doc.page_count = page_count
    job.progress = 30
    job.current_step = "chunking"
    doc.processing_status = "chunking"
    db.commit()

    # ── Step 2: Chunk text ───────────────────────────────────────────────────
    logger.info("[Pipeline] Chunking text for document %s", document_id)
    chunks = chunk_text(full_text)
    chunk_count = len(chunks)
    logger.info("[Pipeline] Produced %d chunks for document %s", chunk_count, document_id)

    doc.chunk_count = chunk_count
    job.progress = 60
    job.current_step = "embedding"
    doc.processing_status = "embedding"
    db.commit()

    # ── Step 3: Embed + store in Chroma Cloud ────────────────────────────────
    logger.info("[Pipeline] Uploading %d chunks to Chroma Cloud for document %s", chunk_count, document_id)
    _store_in_chroma(doc, chunks)

    # ── Done ─────────────────────────────────────────────────────────────────
    doc.processing_status = "processed"
    job.status = "completed"
    job.progress = 100
    job.current_step = "done"
    job.completed_at = datetime.now(timezone.utc)
    db.commit()
    logger.info("[Pipeline] ✅ Completed document %s (%d chunks)", document_id, chunk_count)


def _store_in_chroma(doc, chunks: list[str]) -> None:
    """
    Upload chunks to the user's Chroma Cloud collection.
    Dense (Qwen) + sparse (Splade) embeddings are generated by Chroma Cloud.
    """
    from app.core.chroma import add_chunks_to_chroma

    add_chunks_to_chroma(
        user_id=str(doc.owner_id),
        document_id=str(doc.id),
        document_title=doc.title,
        chunks=chunks,
    )


def _mark_failed(db, document_id: str, error: str) -> None:
    """Mark the document and its job as failed."""
    try:
        from app.models.document import Document
        from app.models.processing_job import ProcessingJob

        doc = db.query(Document).filter(Document.id == document_id).first()
        job = (
            db.query(ProcessingJob)
            .filter(ProcessingJob.document_id == document_id)
            .order_by(ProcessingJob.started_at.desc())
            .first()
        )
        if doc:
            doc.processing_status = "failed"
        if job:
            job.status = "failed"
            job.error_message = error[:500]
            job.completed_at = datetime.now(timezone.utc)
        db.commit()
    except Exception:
        logger.exception("Could not mark document %s as failed", document_id)


def launch_pipeline(document_id: str) -> None:
    """Spawn a daemon thread to run the pipeline without blocking the request."""
    t = threading.Thread(target=run_pipeline, args=(document_id,), daemon=True)
    t.start()
    logger.info("[Pipeline] Launched background thread for document %s", document_id)


__all__ = ["launch_pipeline"]
